apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bdil
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-bdil@sha256:bd7d9f8c974aed2f7d985a48db87d0262b07fc06fb31f8654367099d2d541da6
        name: my-nodejs
        resources: {}
status: {}
